// All user-facing text. Norwegian (nb-NO), klarspråk, du-form.
export const t = {
  appName: 'ting',
  nav: { home: 'Til forsiden', list: 'Oversikt', register: 'Legg til og endre', storage: 'Innstillinger' },
  lock: { lock: 'Lås appen' },
  editing: {
    label: 'Redigering',
    off: 'Redigering er av.',
  },
  vault: {
    setupTitle: 'Velg et passord',
    setupIntro:
      'Passordet låser alt du registrerer, på enheten og i alle kopier. Det lagres ingen steder. Mister du det, er dataene tapt for godt.',
    password: 'Passord',
    show: 'Vis passord',
    hide: 'Skjul passord',
    repeat: 'Gjenta passordet',
    minLength: 'Passordet må ha minst 12 tegn. Bruk gjerne en setning.',
    mismatch: 'Passordene er ikke like.',
    create: 'Krypter og fortsett',
    unlockTitle: 'Låst',
    unlockIntro: 'Skriv inn passordet for å åpne.',
    autoLocked: 'Appen låste seg etter ti minutter uten bruk.',
    unlock: 'Åpne',
    wrong: 'Feil passord.',
    working: 'Åpner …',
    changeTitle: 'Passord',
    changeIntro: 'Dataene krypteres på nytt under det nye passordet. Kopier du har tatt tidligere, åpnes fortsatt med det gamle.',
    current: 'Nåværende passord',
    next: 'Nytt passord',
    change: 'Endre passord',
    changed: 'Passordet er endret.',
    folderForeign: (name: string) =>
      `Mappen «${name}» er kryptert med et annet passord. Skriv det inn for å åpne den. Etterpå bruker begge samme nøkkel.`,
    folderOpen: 'Åpne mappen',
    copyForeign: 'Kopien er kryptert med et annet passord. Skriv det inn for å lese den.',
  },
  search: {
    label: 'Søk',
    open: 'Søk og filtrer',
    close: 'Lukk søk',
    placeholder: 'Skriv her…',
    clear: 'Tøm søk',
    tips: 'Søketips',
    tipsField: 'I søkefeltet',
    tipsList: 'I lista',
    tipsListText: 'Filtrene under søkefeltet snevrer inn lista. Huk av ting for å velge hva rapporten tar med. Ett tegn viser alt som begynner på det tegnet.',
    tipsTableText: 'Rader du har endret, blir stående til du lagrer, også når søket endres.',
    noMatch: (q: string) => `Fant ikke «${q}»`,
    showAll: 'Vis alle ting',
    tipRows: [
      ['sovepose', 'Ord, tåler skrivefeil'],
      ['"sovepose vinter"', 'Nøyaktig frase'],
      ['-sommer', 'Utelat'],
      ['komfort<0', 'Egenskap mindre enn. Også > <= >= ='],
      ['brensel:gass', 'Egenskap inneholder tekst'],
      ['has:bilde', 'Har bilde. Også has:notat og has:vekt'],
      ['kategori:tur', 'Kategori som inneholder'],
      ['kjøpsdato<01.01.26', 'Datoegenskap før en dato'],
    ],
    keysLabel: 'Egenskaper du kan søke på',
  },
  filters: {
    noValues: 'Ingen verdier ennå',
    clearOne: 'Vis alle',
    clearAll: 'Nullstill filtre',
  },
  list: {
    empty: 'Ingenting her ennå',
    noMatch: 'Ingen treff',
    count: (n: number) => (n === 1 ? '1 ting' : `${n} ting`),
    selectedCount: (n: number, total: number) => `${n} av ${total} valgt`,
    loading: 'Laster',
    selectAll: 'Velg alle i lista',
    selectRow: (name: string) => `Velg ${name}`,
    clearSelection: 'Fjern valg',
  },
  report: {
    csv: 'Last ned CSV',
    print: 'Skriv ut eller lagre som PDF',
    scopeSelected: (n: number) => (n === 1 ? 'Rapporten tar med 1 valgt ting' : `Rapporten tar med ${n} valgte ting`),
    scopeVisible: (n: number) => (n === 1 ? 'Rapporten tar med 1 ting i lista' : `Rapporten tar med alle ${n} ting i lista`),
    title: 'Ting',
    subtitle: (date: string, n: number) => `Rapport ${date}. ${n === 1 ? '1 ting' : `${n} ting`}.`,
    name: 'Navn',
    category: 'Kategori',
    note: 'Notat',
    created: 'Opprettet',
  },
  action: {
    save: 'Lagre',
    cancel: 'Avbryt',
    edit: 'Rediger',
    delete: 'Slett',
    back: 'Tilbake',
    addSpec: 'Legg til spesifikasjon',
    removeSpec: 'Fjern spesifikasjon',
    choosePhoto: 'Velg bilde',
    removePhoto: 'Fjern bilde',
    yes: 'Ja',
    no: 'Nei',
  },
  form: {
    editTitle: 'Rediger',
    name: 'Navn',
    category: 'Kategori',
    photo: 'Bilde',
    photoHint: 'Valgfritt',
    specs: 'Spesifikasjoner',
    specKey: 'Egenskap',
    specValue: 'Verdi',
    specUnit: 'Enhet',
    note: 'Notat',
  },
  detail: {
    specs: 'Spesifikasjoner',
    noSpecs: 'Ingen spesifikasjoner',
    note: 'Notat',
    created: 'Opprettet',
    updated: 'Oppdatert',
    notFound: 'Fant ikke denne tingen',
    photoAlt: (name: string) => `Bilde av ${name}`,
  },
  confirm: {
    delete: (name: string) => `Slett «${name}»? Dette kan ikke angres.`,
    deleteMany: (n: number) => (n === 1 ? 'Slett 1 ting? Dette kan ikke angres.' : `Slett ${n} ting? Dette kan ikke angres.`),
    unsaved: 'Du har endringer som ikke er lagret. Forlat siden likevel?',
    saveOrDiscard: 'Vil du lagre?',
  },
  table: {
    selectAll: 'Velg alle',
    selectRow: (name: string) => `Velg ${name === '' ? 'ny rad' : name}`,
    name: 'Navn',
    category: 'Kategori',
    note: 'Notat',
    addRow: 'Ny ting',
    addColumn: 'Ny egenskap',
    columnKey: 'Navn på egenskap',
    columnKeyExample: 'For eksempel Komforttemperatur',
    columnType: 'Felttype',
    types: { text: 'Tekst', choice: 'Nedtrekk', number: 'Tall', date: 'Dato' },
    columnOptions: 'Valg',
    columnOptionsHint: 'Skill med komma. Verdier som allerede er brukt, kommer i tillegg.',
    columnOptionsExample: 'For eksempel Sovepose, Telt, Kokeapparat',
    columnUnit: 'Enhet',
    columnUnitOptional: 'Valgfritt',
    columnUnitExample: 'For eksempel °C',
    columnHint:
      'Nedtrekk: Velg blant verdiene som finnes, eller skriv en ny. Tall: Skriv bare tallet, 1250 og ikke 1250 gram. Enheten gjelder hele kolonnen. Dato: Skriv 19.09.26.',
    columnAdd: 'Legg til egenskap',
    unitOptions: ['kr', '°C', 'gram', 'kg', 'cm', 'mm', 'm', 'liter', 'ml', 'stk', 'år'],
    columnAdded: (key: string) => `Egenskapen «${key}» er lagt til.`,
    removeColumn: 'Fjern',
    hideColumn: 'Skjul',
    removeColumnConfirm: (key: string, n: number) =>
      `Egenskapen «${key}» brukes av ${n === 1 ? '1 ting' : `${n} ting`}. Fjern den fra alle? Dette kan ikke angres.`,
    removeColumnAction: 'Fjern',
    columnMenu: (key: string) => `Valg for ${key}`,
    sortBy: (key: string) => `Sorter etter ${key}`,
    resize: (key: string) => `Endre bredde på ${key}`,
    resizeHint: 'Dra for å endre bredde. Dobbeltklikk for å tilpasse innholdet.',
    renameColumn: 'Endre',
    showCategory: (label: string) => `Vis ${label} igjen`,
    hideCategoryConfirm: (label: string) =>
      `Skjul «${label}»? Verdiene blir liggende, og kolonnen kan hentes fram igjen.`,
    hideCategoryAction: 'Skjul',
    nameCannotGo: 'Navn kan ikke fjernes. Det er navnet du finner tingen på.',
    renameSave: 'Lagre navn',
    renameCancel: 'Avbryt',
    moveLeft: 'Flytt til venstre',
    moveRight: 'Flytt til høyre',
    removeRow: 'Fjern rad',
    deleteSelected: (n: number) => `Slett valgte (${n})`,
    unsaved: (n: number) => (n === 1 ? '1 endring ikke lagret' : `${n} endringer ikke lagret`),
    saved: 'Lagret',
    nothingToSave: 'Ingen endringer',
    cell: (name: string, col: string) => `${col} for ${name === '' ? 'ny rad' : name}`,
  },
  error: {
    nameMissing: 'Navn mangler. Skriv inn et navn.',
    specIncomplete: 'Hver spesifikasjon trenger både egenskap og verdi.',
    saveFailed: 'Kunne ikke lagre. Prøv igjen.',
    crashed: 'Noe gikk galt. Dataene dine er trygge. Last siden på nytt for å fortsette.',
    reload: 'Last på nytt',
    rowsMissingName: (n: number) => (n === 1 ? '1 rad mangler navn.' : `${n} rader mangler navn.`),
    rowsMissingCategory: (n: number) => (n === 1 ? '1 rad mangler kategori.' : `${n} rader mangler kategori.`),
    categoryMissing: 'Kategori mangler. Velg eller skriv en kategori.',
    columnExists: 'Denne egenskapen finnes allerede.',
    notNumbers: (n: number, key: string) => (n === 1 ? `1 verdi i ${key} er ikke et tall.` : `${n} verdier i ${key} er ikke tall.`),
    notDates: (n: number, key: string) => (n === 1 ? `1 verdi i ${key} er ikke en dato.` : `${n} verdier i ${key} er ikke datoer.`),
  },
  notice: {
    update: 'Ny versjon klar. Trykk for å oppdatere.',
  },
  storage: {
    title: 'Innstillinger',
    folderTitle: 'Mappe på disk',
    folderIntro:
      'Koble appen til en mappe. Appen lagrer ting.json og bildene der hver gang du lagrer. Kopier mappen når du vil ta vare på alt.',
    unsupported: 'Denne nettleseren kan ikke koble appen til en mappe. Bruk Chrome eller Edge, eller last ned en kopi under.',
    choose: 'Velg mappe',
    checking: 'Sjekker mappen',
    needsPermission: (name: string) => `Mappen «${name}» trenger tillatelse på nytt. Fram til da lagres alt bare i nettleseren.`,
    grant: 'Gi tilgang',
    connected: (name: string) => `Lagres i mappen «${name}».`,
    lastWritten: (time: string) => `Sist skrevet ${time}.`,
    loaded: 'Lastet fra mappen.',
    disconnect: 'Koble fra',
    error: (name: string, message: string) => `Kunne ikke skrive til «${name}». ${message}`,
    copyTitle: 'Kopi',
    copyIntro: 'Én fil med alle ting og bilder. Passer som ekstra sikkerhet, eller for å flytte alt til en annen enhet.',
    download: 'Last ned kopi',
    restore: 'Gjenopprett fra kopi',
    restoreConfirm: (n: number) => `Erstatt alt som ligger her med ${n === 1 ? '1 ting' : `${n} ting`} fra filen? Dette kan ikke angres.`,
    restoreDone: (n: number) => `Gjenopprettet ${n === 1 ? '1 ting' : `${n} ting`}.`,
    restoreFailed: 'Filen ble ikke gjenkjent som en kopi fra Ting.',
    copyIsSealed: 'Kopien er kryptert og kan bare åpnes med passordet ditt.',
    replace: 'Erstatt',
  },
} as const
