// All user-facing text. Norwegian (nb-NO), klarspråk, du-form.
export const t = {
  appName: 'ting',
  nav: { home: 'Til forsiden', list: 'Oversikt', settings: 'Innstillinger', settingsStalled: 'Innstillinger. Lagring til mappen har stoppet' },
  lock: { lock: 'Lås appen' },
  vault: {
    setupTitle: 'Velg et passord',
    passphrase: 'Passord',
    show: 'Vis passord',
    hide: 'Skjul passord',
    repeat: 'Gjenta passordet',
    minLength: 'Passordet må ha minst 12 tegn. Bruk gjerne en setning.',
    mismatch: 'Passordene er ikke like. Skriv det samme i begge feltene.',
    create: 'Krypter og fortsett',
    unlockTitle: 'Appen er låst',
    autoLocked: 'Appen låste seg etter 10 minutter uten bruk',
    unlock: 'Lås opp',
    wrong: 'Feil passord',
    working: 'Låser opp…',
    // Lås og passord: the idle lock, Face ID or Touch ID in place of the
    // passphrase (a passkey), and the passphrase itself
    lockTitle: 'Lås og passord',
    autoLockOption: 'Lås appen etter 10 minutter uten bruk',
    passkeyOption: 'Lås opp med Face ID eller Touch ID',
    passkeyWhere: 'Gjelder bare denne enheten',
    passkeyUnlock: 'Lås opp med Face ID eller Touch ID',
    passkeyFailed: 'Face ID eller Touch ID virket ikke. Lås opp med passordet.',
    passkeyNotHere: 'Denne enheten kan ikke låse opp appen med Face ID eller Touch ID',
    changeTitle: 'Passord',
    current: 'Nåværende passord',
    next: 'Nytt passord',
    change: 'Endre passord',
    // Beside the row's own title the verb is enough; the full text stays the accessible name
    changeShort: 'Endre',
    changed: 'Du har endret passordet',
    folderForeign: (name: string) =>
      `Mappen «${name}» er låst med et annet passord. Skriv det inn for å åpne mappen. Fra nå av låser du opp appen med det passordet.`,
    folderOpen: 'Åpne mappen',
    // The account a password manager files the passphrase under
    keychainName: 'Ting',
  },
  search: {
    label: 'Søk',
    open: 'Søk og filtrer',
    close: 'Lukk søk',
    placeholder: 'Søk på navn eller egenskap',
    clear: 'Tøm søk',
    tips: 'Søketips',
    noMatch: (q: string) => `Fant ikke «${q}»`,
    showAll: 'Vis alle ting',
  },
  // The category line over the table: which categories the register shows
  categoryPicker: {
    label: 'Velg kategori',
    all: 'Alle',
    change: (current: string) => `Kategori: ${current}. Velg en annen`,
    clear: 'Fjern alle valgte',
  },
  // Endre egenskaper: several properties changed or removed at once
  properties: {
    edit: 'Endre egenskaper',
    title: 'Egenskaper',
    hint: 'Et nytt navn eller en ny felttype gjelder alle ting. Kategori endrer du under Endre kategorier.',
    name: (key: string) => `Navn på ${key}`,
    type: (key: string) => `Felttype for ${key}`,
    unit: (key: string) => `Enhet for ${key}`,
    scopeAll: 'Alle kategorier',
    scopeNone: 'Ingen kategorier',
    scopeButton: (key: string, where: string) => `${key} brukes i: ${where}. Endre`,
    scopeTitle: (key: string) => `Kategorier for ${key}`,
    remove: (key: string) => `Fjern ${key}`,
    keep: (key: string) => `Behold ${key}`,
    confirmRemove: (keys: string, n: number) =>
      `${keys} har verdier på ${n === 1 ? '1 ting' : `${n} ting`}. Verdiene forsvinner fra alle. Du kan ikke angre.`,
    removeAndSave: 'Fjern og lagre',
    dirtyFirst: 'Lagre eller forkast endringene i tabellen først',
  },
  // A Valgliste's alternatives, opened from its line in Endre egenskaper
  options: {
    edit: 'Endre alternativer',
    count: (n: number) => (n === 0 ? 'Ingen alternativer' : n === 1 ? '1 alternativ' : `${n} alternativer`),
    button: (count: string, key: string) => `${count} for ${key}`,
    title: (key: string) => `Alternativer for ${key}`,
    hint: 'Endringen gjelder alle ting som har alternativet. To alternativer med samme navn blir ett.',
    name: 'Navn på alternativ',
    add: 'Nytt alternativ',
    newRow: 'Nytt',
    confirmRemove: (values: string, n: number) =>
      `${n === 1 ? '1 ting' : `${n} ting`} har ${values}. Verdien forsvinner fra ${n === 1 ? 'den' : 'dem'}. Du kan ikke angre.`,
  },
  // Ticked things: what can be done with all of them at once
  selection: {
    count: (n: number) => `${n} valgt`,
    edit: 'Endre verdi',
    editTitle: (n: number) => (n === 1 ? 'Endre 1 ting' : `Endre ${n} ting`),
    property: 'Egenskap',
    value: 'Ny verdi',
    apply: 'Endre',
    editHint: 'Et tomt felt fjerner verdien. Ingenting lagres før du trykker Lagre.',
    print: 'Skriv ut',
    csv: 'Last ned',
    delete: 'Slett',
    clear: 'Fjern valget',
    printing: (n: number) => (n === 1 ? 'Bare den valgte tingen kommer med.' : `Bare de ${n} valgte tingene kommer med.`),
  },
  // Endre kategorier: names, icons and new categories
  categories: {
    edit: 'Endre kategorier',
    title: 'Kategorier',
    hint: 'Et nytt navn gjelder alle ting i kategorien. To kategorier med samme navn blir én.',
    name: 'Navn på kategori',
    add: 'Ny kategori',
    newRow: 'Ny',
    iconButton: (category: string, icon: string) => `Symbol for ${category}: ${icon}. Velg et annet`,
    pickerTitle: (category: string) => `Velg symbol for ${category}`,
    search: 'Søk etter symbol',
    suggested: 'foreslått ut fra navnet',
    byName: 'Velg ut fra navnet',
    properties: (n: number) => (n === 0 ? 'Ingen egenskaper' : n === 1 ? '1 egenskap' : `${n} egenskaper`),
    propertiesButton: (count: string, category: string) => `${count} i ${category}`,
    propertiesTitle: (category: string) => `Egenskaper i ${category}`,
  },
  filters: {
    showAll: (n: number) => `Vis alle ${n}`,
    // A place column gets one menu per level: the column's own name for the
    // first, then the name with the level after it.
    level: (key: string, level: number) => (level === 1 ? key : `${key} ${level}`),
    narrow: (label: string) => `Søk i ${label.toLocaleLowerCase('nb')}`,
    clearOne: 'Fjern filteret',
    clearAll: 'Fjern alle filtre',
  },
  list: {
    empty: 'Registeret er tomt',
    noMatch: 'Ingen treff',
    loading: 'Laster…',
  },
  summary: {
    things: (n: number) => (n === 1 ? '1 ting' : `${n} ting`),
    shown: (n: number, total: number) => `${n} av ${total} ting`,
    total: (key: string, amount: string) => `${key} totalt: ${amount}`,
  },
  report: {
    csv: 'Last ned CSV',
    print: 'Skriv ut',
    pick: 'Ta med i utskriften',
    docTitle: 'Ting',
    subtitle: (date: string, n: number) => `Rapport ${date}. ${n === 1 ? '1 ting' : `${n} ting`}.`,
    // Two choices that change the shape of the paper: headings that add up,
    // and a photo beside each thing.
    groupBy: 'Grupper etter',
    groupNone: 'Ingen',
    groupRest: (key: string) => `Uten ${key.toLocaleLowerCase('nb')}`,
    withPhotos: 'Ta med bilder',
    sum: (key: string, amount: string) => `${key}: ${amount}`,
    grandTotal: 'Til sammen',
  },
  action: {
    save: 'Lagre',
    cancel: 'Avbryt',
    close: 'Lukk',
    delete: 'Slett',
    back: 'Tilbake',
    pickAll: 'Velg alle',
    pickNone: 'Fjern alle',
    takePhoto: 'Ta bilde',
    removePhoto: 'Fjern bilde',
    removePhotos: 'Fjern bildene',
    // Several photos per thing: the first is the one the table and the report
    // show, and any of them can be made the first.
    addPhoto: 'Legg til bilde',
    makeFirstPhoto: 'Gjør til hovedbilde',
    firstPhoto: 'Hovedbilde',
    removePhotoAt: (n: number) => `Fjern bilde ${n}`,
  },
  add: {
    title: 'Ny ting',
    // The photo thumbnail, named for the thing it shows
    thing: 'tingen',
    photos: (name: string, n: number) =>
      n === 0 ? `Legg til bilde av ${name}` : n === 1 ? `Bilde av ${name}` : `${n} bilder av ${name}`,
    saved: (name: string) => `«${name}» lagret`,
    missingName: 'Tingen må ha et navn',
    // The values to tap under a field, named for the field
    suggestions: (label: string) => `${label}: Forslag`,
    // The field on top of a choice's dropdown
    newValue: 'Ny verdi',
    newValueFor: (label: string) => `${label}: Ny verdi`,
  },
  barcode: {
    label: 'Strekkode',
    scan: 'Skann strekkode',
    scanning: 'Leser…',
    read: (format: string) => `Lest som ${format}`,
    none: 'Fant ingen strekkode i bildet',
    // In a book category the field is the book's ISBN
    isbn: 'ISBN',
    scanIsbn: 'Skann ISBN',
    lookup: 'Slå opp på nett',
    looking: 'Slår opp…',
    found: (source: string) => `Hentet fra ${source}`,
    known: (n: number) => `Registeret har ${n} med denne koden`,
    notFound: 'Fant ikke boka i oppslagsverkene',
    offline: 'Ingen nettforbindelse',
    failed: 'Fikk ikke svar fra oppslagsverkene',
  },
  detail: {
    properties: 'Egenskaper',
    photos: 'Bilder',
    noProperties: 'Ingen egenskaper',
    notFound: 'Fant ikke denne tingen',
    photoAlt: (name: string) => `Bilde av ${name}`,
    edit: (label: string) => `Endre ${label.toLocaleLowerCase('nb')}`,
  },
  confirm: {
    delete: (name: string) => `Slett «${name}»? Du kan ikke angre.`,
    deleteMany: (n: number) => (n === 1 ? 'Slett 1 ting? Du kan ikke angre.' : `Slett ${n} ting? Du kan ikke angre.`),
    unsaved: 'Du har endringer som ikke er lagret. Forlat siden likevel?',
    saveOrDiscard: 'Du har endringer som ikke er lagret',
    discard: 'Forkast endringene',
  },
  table: {
    selectAll: 'Velg alle',
    selectRow: (name: string) => `Velg ${name === '' ? 'ny rad' : name}`,
    name: 'Navn',
    addRow: 'Legg til ting',
    addColumn: 'Legg til egenskap',
    // Plus opens a menu: a thing (a row) or a property (a column)
    add: 'Legg til',
    addColumnMenu: 'Legg til/endre egenskap (kolonne)',
    // Under the column form: help for the field in use. For the name, the
    // properties that already exist and start with what is typed
    columnHelp: {
      similar: 'Finnes fra før',
      everywhere: (key: string) => `«${key}» finnes i alle kategorier`,
      here: (key: string, where: string) => `«${key}» finnes allerede i ${where}`,
      elsewhere: (key: string, where: string) => `«${key}» finnes i ${where}`,
      shared: (key: string, where: string, here: string) =>
        `«${key}» finnes i ${where}. ${here} får den samme egenskapen hvis du legger den til.`,
      unused: (key: string, here: string) =>
        `«${key}» finnes, men ingen kategori bruker den.${here === '' ? '' : ` ${here} får den hvis du legger den til.`}`,
      types: {
        text: 'Fritekst, som en kommentar eller et serienummer. Lenker blir klikkbare på tingens side.',
        choice: 'Faste verdier å velge mellom, som Status eller Farge. Du kan filtrere på dem og gruppere utskriften etter dem.',
        number: 'Skriv bare tallet i cellene. Enheten velger du i neste felt.',
        date: 'En dato, som 19.09.26. Filteret viser årene.',
        path: 'Hele veien inn til plassen, som Loftsbod › Hylle 2 › Boks 4. Du får ett filter per nivå.',
      },
      options: 'Skriv alternativene adskilt med komma: «Bøker, Film, Musikk». Med eller uten mellomrom etter komma.',
      unit: 'Velg i lista eller skriv din egen. Kolonner i kr får en sum.',
      scope: 'Uten hake hører egenskapen til alle kategorier',
    },
    wrap: 'Bryt lang tekst i tabellen',
    columnKey: 'Navn på egenskap',
    columnType: 'Felttype',
    types: { text: 'Tekst', choice: 'Valgliste', number: 'Tall', date: 'Dato', path: 'Sti' },
    columnOptions: 'Alternativer',
    columnUnit: 'Enhet',
    columnUnitOptional: 'Valgfritt',
    columnAdd: 'Legg til',
    // Symbol and the word for it: the list shows both, the column stores the symbol
    unitOptions: [
      ['kr', 'kroner'],
      ['°C', 'grader celsius'],
      ['g', 'gram'],
      ['kg', 'kilogram'],
      ['mm', 'millimeter'],
      ['cm', 'centimeter'],
      ['m', 'meter'],
      ['ml', 'milliliter'],
      ['l', 'liter'],
      ['stk', 'stykk'],
      ['år', 'år'],
    ],
    removeColumn: 'Fjern',
    // The columns the view leaves out: empty here, or the same on every row
    showMore: (n: number) => (n === 1 ? 'Vis 1 kolonne til' : `Vis ${n} kolonner til`),
    hideMore: 'Vis færre kolonner',
    // What a column is for while categories are in view: the column form, and the column menu with one
    onlyIn: (category: string) => `Bruk bare i ${category}`,
    alsoIn: (category: string) => `Bruk også i ${category}`,
    notIn: (category: string) => `Ikke bruk i ${category}`,
    removeColumnConfirm: (key: string, n: number) =>
      `Egenskapen «${key}» brukes av ${n === 1 ? '1 ting' : `${n} ting`}. Fjern den fra alle? Du kan ikke angre.`,
    removeColumnAction: 'Fjern',
    columnMenu: (key: string) => `Valg for ${key}`,
    sortBy: (key: string) => `Sorter etter ${key}`,
    resize: (key: string) => `Endre bredde på ${key}`,
    resizeHint: 'Dra for å endre bredde. Dobbeltklikk for å tilpasse bredden til innholdet.',
    renameColumn: 'Endre navn',
    renameSave: 'Lagre navn',
    renameCancel: 'Avbryt',
    unsaved: (n: number) => (n === 1 ? '1 endring ikke lagret' : `${n} endringer ikke lagret`),
    cell: (name: string, col: string) => `${col} for ${name === '' ? 'ny rad' : name}`,
  },
  error: {
    saveFailed: 'Kunne ikke lagre. Prøv på nytt.',
    crashed: 'Noe gikk galt, men dataene dine er bevart. Last siden på nytt for å fortsette.',
    reload: 'Last på nytt',
    rowsMissingName: (n: number) => (n === 1 ? '1 rad mangler navn.' : `${n} rader mangler navn.`),
    columnExists: 'Denne egenskapen finnes allerede',
    notNumbers: (n: number, key: string) => (n === 1 ? `1 verdi i ${key} er ikke et tall.` : `${n} verdier i ${key} er ikke tall.`),
    notDates: (n: number, key: string) => (n === 1 ? `1 verdi i ${key} er ikke en dato.` : `${n} verdier i ${key} er ikke datoer.`),
  },
  notice: {
    update: 'Oppdater til ny versjon',
  },
  // How to install, where the browser has no prompt of its own. Safari on an
  // iPhone keeps Del behind ••• (iOS 26 and later); on an iPad and in the
  // other iPhone browsers Del is on the bar itself.
  install: {
    iosMore: 'Trykk på •••, velg Del og så Legg til på Hjem-skjerm',
    iosShare: 'Trykk på Del og velg Legg til på Hjem-skjerm',
    macSafari: 'Klikk på Del og velg Legg til i Dock',
    other: 'Velg Installer eller Legg til på startskjerm i menyen til nettleseren. Bruk Chrome, Edge eller Safari hvis valget mangler.',
  },
  // In a browser tab: the app as a demo, and the way to the real one
  demo: {
    download: 'Last ned gratis',
    notice: 'Dette er en demo med eksempler. Last ned appen for å registrere tingene dine.',
  },
  // Before a passphrase: the line under the top bar
  trial: {
    notice: 'Du bruker appen i prøvemodus. Det du legger til, blir borte når du lukker den.',
    // A phone closes the app on its own, so the phone says when, not who
    noticePhone: 'Det du legger til, blir borte når appen lukkes',
    setPassphrase: 'Velg passord for å bevare det',
    why: 'Passordet krypterer alt du legger til',
    lost: 'Ingen kan åpne registeret hvis du mister passordet',
    folderFirst: 'Velg et passord først',
    done: 'Passord valgt. Alt du har lagt til, blir bevart.',
  },
  settings: {
    title: 'Innstillinger',
    storageTitle: 'Lagring',
    columnsTitle: 'Tilpass visning',
    columnsList: 'Egenskaper i tabellen',
    columnsShown: (shown: number, total: number) => `${shown} av ${total} vises`,
    folderTitle: 'Lagringsmappe',
    folderNone: 'Registeret ligger bare i denne nettleseren og blir borte hvis du sletter nettstedsdata',
    unsupported: 'Denne nettleseren kan ikke koble appen til en mappe. Bruk Chrome eller Edge, eller ta en sikkerhetskopi med «Eksporter registeret».',
    choose: 'Velg mappe',
    chooseShort: 'Velg',
    checking: 'Sjekker mappen…',
    needsPermission: (name: string) => `Mappen «${name}» trenger tillatelse på nytt. Frem til da lagrer appen bare i nettleseren.`,
    grant: 'Gi tilgang',
    connected: (name: string) => `Appen lagrer i mappen «${name}».`,
    lastWritten: (time: string) => `Sist lagret kl. ${time}.`,
    disconnect: 'Koble fra',
    error: (name: string) => `Kunne ikke lagre i «${name}». Prøv på nytt, eller koble til mappen på nytt.`,
  },
  // Ny fra kvittering: the photo of a receipt read on the device into things
  receipt: {
    fromReceipt: 'Fra kvittering',
    title: 'Ny fra kvittering',
    pick: 'Ta bilde av kvitteringen',
    reading: 'Leser kvitteringen…',
    thumb: 'Kvitteringen',
    retake: 'Ta nytt bilde',
    adjust: 'Juster hjørnene',
    adjustHint: 'Dra hvert hjørne ut til kanten av kvitteringen',
    useCorners: 'Bruk hjørnene',
    corner: (n: number) => `Hjørne ${n}. Flytt det med piltastene`,
    things: 'Ting på kvitteringen',
    include: (name: string) => `Ta med ${name === '' ? 'denne' : name}`,
    lineName: (n: number) => `Navn på ting ${n}`,
    lineThing: (n: number) => `ting ${n}`,
    linePrice: (n: number) => `Pris for ting ${n}, i kroner`,
    addLine: 'Legg til en ting',
    unbalanced: (sum: string, total: string) => `Prisene blir ${sum} til sammen, men kvitteringen sier ${total}. Sjekk prisene.`,
    noLines: 'Fant ingen varer. Skriv dem inn selv, eller ta et nytt bilde rett ovenfra.',
    failed: 'Kunne ikke lese kvitteringen. Ta et nytt bilde rett ovenfra, med godt lys.',
    save: (n: number) => (n === 1 ? 'Lagre 1 ting' : `Lagre ${n} ting`),
    // Innstillinger: receipt reading is a download, so it is switched on first
    settingsTitle: 'Kvitteringer',
    option: 'Les tekst på kvitteringer',
    what: 'Appen laster ned KI-modeller og verktøy på ~ 45 MB, så den kan kjenne igjen tekst på kvitteringer',
    downloading: 'Laster ned tekstgjenkjenning…',
    ready: 'Tekstgjenkjenning lagt til og aktivert',
    downloadFailed: 'Nedlastingen stoppet. Prøv igjen når du har nett.',
  },
  // The foot of Innstillinger
  about: {
    privacy: 'Personvern',
    source: 'Kildekode',
    version: (version: string) => `v${version}`,
    author: 'elzacka',
  },
  // The register as one sealed file: exported as a backup or to another device, imported by merge or replace
  sync: {
    importTitle: 'Importer til registeret',
    importWhat: 'Velg fil fra denne enheten eller delt fra en annen enhet',
    pick: 'Velg fil',
    imported: (date: string, time: string) => `Sist importert ${date} kl. ${time}.`,
    exportTitle: 'Eksporter registeret',
    exportWhat: 'Lagre fil fra denne enheten som en sikkerhetskopi eller for å dele med en annen enhet',
    exportButton: 'Eksporter/del fil',
    exported: (date: string, time: string) => `Sist eksportert ${date} kl. ${time}.`,
    // Asked only when the register already holds things
    ask: (held: number, incoming: number) =>
      `Registeret har ${held} ting fra før, og fila har ${incoming}. Vil du slå sammen endringene fra begge, eller erstatte alt i registeret med innholdet i fila? Du kan ikke angre hvis du erstatter alt.`,
    askAdopt: 'Hvis du slår sammen, bruker du passordet fra fila når du låser opp appen etterpå.',
    // A plain file or a trial cannot merge
    replaceOnly: (incoming: number) => `Erstatt alt i registeret med ${incoming} ting fra fila? Du kan ikke angre.`,
    merge: 'Slå sammen',
    replace: 'Erstatt alt',
    replaced: (n: number) => `${n} ting importert`,
    adopted: 'Fra nå av låser du opp appen med passordet fra fila',
    // After a merge: where the file came from, when it was made, what changed
    from: (device: string | undefined, date: string, time: string) =>
      device ? `Fil fra ${device}, laget ${date} kl. ${time}` : `Fil laget ${date} kl. ${time}`,
    counts: (added: number, changed: number, deleted: number) =>
      [
        added > 0 ? `${added} ${added === 1 ? 'ny' : 'nye'}` : null,
        changed > 0 ? `${changed} endret` : null,
        deleted > 0 ? `${deleted} slettet` : null,
      ]
        .filter(Boolean)
        .join(', '),
    layout: 'Egenskaper oppdatert',
    both: (n: number) => `${n === 1 ? '1 ting' : `${n} ting`} var endret på begge enhetene. Den nyeste endringen er beholdt.`,
    nothing: (date: string, time: string) => `Ingenting nytt. Fila er laget ${date} kl. ${time}.`,
    future: 'Klokka på den andre enheten går mer enn ett døgn foran. Sjekk dato og klokkeslett der.',
    passphraseChanged: 'Passordet er endret på den andre enheten. Bruk det nye passordet når du låser opp.',
    newer: 'Fila er laget av en nyere versjon av Ting. Oppdater appen og prøv på nytt.',
    notTing: 'Denne fila er ikke fra Ting. Velg en fil du har eksportert fra Ting.',
    foreign: 'Fila er låst med et annet passord. Skriv inn passordet appen hadde da fila ble eksportert.',
  },
} as const
