// All user-facing text. Norwegian (nb-NO), klarspråk, du-form.
export const t = {
  appName: 'ting',
  nav: { home: 'Til forsiden', list: 'Oversikt', storage: 'Innstillinger', storageStalled: 'Innstillinger. Lagring til mappen har stoppet' },
  lock: { lock: 'Lås appen' },
  vault: {
    setupTitle: 'Velg et passord',
    password: 'Passord',
    show: 'Vis passord',
    hide: 'Skjul passord',
    repeat: 'Gjenta passordet',
    minLength: 'Passordet må ha minst 12 tegn. Bruk gjerne en setning.',
    mismatch: 'Passordene er ikke like. Skriv det samme i begge feltene.',
    create: 'Krypter og fortsett',
    unlockTitle: 'Appen er låst',
    autoLocked: 'Appen låste seg etter 10 minutter uten aktivitet.',
    unlock: 'Lås opp',
    wrong: 'Feil passord.',
    working: 'Låser opp…',
    // How this device locks and opens: the idle lock, and Face ID or Touch ID
    // in place of the passphrase (a passkey)
    lockTitle: 'Lås',
    autoLockOption: 'Lås appen etter 10 minutter uten bruk',
    passkeyOption: 'Lås opp med Face ID eller Touch ID på denne enheten',
    passkeyUnlock: 'Lås opp med Face ID eller Touch ID',
    passkeyFailed: 'Face ID eller Touch ID virket ikke. Lås opp med passordet.',
    passkeyNotHere: 'Denne enheten kan ikke låse opp appen med Face ID eller Touch ID.',
    changeTitle: 'Passord',
    changeWhat:
      'Passordet krypterer alt du registrerer, på enheten, i lagringsmappen og i sikkerhetskopiene. Gjenoppretter du fra en sikkerhetskopi og appen ber om passord, bruker du passordet du hadde da du lastet den ned.',
    current: 'Nåværende passord',
    next: 'Nytt passord',
    change: 'Endre passord',
    changed: 'Passordet er endret.',
    folderForeign: (name: string) =>
      `Mappen «${name}» er låst med et annet passord. Skriv det inn for å åpne mappen. Fra nå av låser du opp appen med det passordet.`,
    folderOpen: 'Åpne mappen',
    copyForeign: 'Kopien er kryptert med et annet passord. Skriv det inn for å lese den.',
    // The account a password manager files the passphrase under
    keychainName: 'Ting',
  },
  search: {
    label: 'Søk',
    open: 'Søk og filtrer',
    close: 'Lukk søk',
    placeholder: 'Søk på navn eller egenskap',
    clear: 'Tøm søk',
    tips: 'Søketips',
    noMatch: (q: string) => `Fant ikke «${q}»`,
    showAll: 'Vis alle ting',
  },
  // The category line over the table: which categories the register shows
  view: {
    label: 'Velg kategori',
    all: 'Alle',
    change: (current: string) => `Kategori: ${current}. Velg en annen`,
    clear: 'Fjern alle valgte',
  },
  // Endre egenskaper: several properties changed or removed at once
  properties: {
    edit: 'Endre egenskaper',
    title: 'Egenskaper',
    hint: 'Endrer du navn eller felttype, gjelder det alle ting. Kategori endrer du under Endre kategorier.',
    name: (key: string) => `Navn på ${key}`,
    type: (key: string) => `Felttype for ${key}`,
    unit: (key: string) => `Enhet for ${key}`,
    scopeAll: 'Alle kategorier',
    scopeButton: (key: string, where: string) => `${key} brukes i: ${where}. Endre`,
    scopeTitle: (key: string) => `Kategorier for ${key}`,
    remove: (key: string) => `Fjern ${key}`,
    keep: (key: string) => `Behold ${key}`,
    confirmRemove: (keys: string, n: number) =>
      `${keys} har verdier på ${n === 1 ? '1 ting' : `${n} ting`}. Verdiene forsvinner fra alle. Du kan ikke angre.`,
    removeAndSave: 'Fjern og lagre',
    dirtyFirst: 'Lagre eller forkast endringene i tabellen først.',
  },
  // Ticked things: what can be done with all of them at once
  selection: {
    count: (n: number) => `${n} valgt`,
    edit: 'Endre verdi',
    editTitle: (n: number) => (n === 1 ? 'Endre 1 ting' : `Endre ${n} ting`),
    property: 'Egenskap',
    value: 'Ny verdi',
    apply: 'Endre',
    editHint: 'Et tomt felt fjerner verdien. Ingenting lagres før du trykker Lagre.',
    print: 'Skriv ut',
    csv: 'Last ned',
    delete: 'Slett',
    clear: 'Fjern valget',
    printing: (n: number) => (n === 1 ? 'Bare den valgte tingen kommer med.' : `Bare de ${n} valgte tingene kommer med.`),
  },
  // Endre kategorier: names, icons and new categories
  categories: {
    edit: 'Endre kategorier',
    title: 'Kategorier',
    hint: 'Endrer du et navn, endres det på alle ting i kategorien. Gir du to kategorier samme navn, blir de én.',
    name: 'Navn på kategori',
    add: 'Ny kategori',
    newRow: 'Ny',
    iconButton: (category: string, icon: string) => `Symbol for ${category}: ${icon}. Velg et annet`,
    pickerTitle: (category: string) => `Velg symbol for ${category}`,
    search: 'Søk etter symbol',
    suggested: 'foreslått ut fra navnet',
    byName: 'Velg ut fra navnet',
  },
  filters: {
    showAll: (n: number) => `Vis alle ${n}`,
    // A place column gets one menu per level: the column's own name for the
    // first, then the name with the level after it.
    level: (key: string, level: number) => (level === 1 ? key : `${key} ${level}`),
    narrow: (label: string) => `Søk i ${label.toLocaleLowerCase('nb')}`,
    clearOne: 'Fjern filteret',
    clearAll: 'Fjern alle filtre',
  },
  list: {
    empty: 'Registeret er tomt.',
    noMatch: 'Ingen treff',
    loading: 'Laster…',
  },
  summary: {
    things: (n: number) => (n === 1 ? '1 ting' : `${n} ting`),
    shown: (n: number, total: number) => `${n} av ${total} ting`,
    total: (key: string, amount: string) => `${key} totalt: ${amount}`,
  },
  report: {
    csv: 'Last ned CSV',
    print: 'Skriv ut',
    pick: 'Ta med i utskriften',
    pickAll: 'Velg alle',
    pickNone: 'Fjern alle',
    docTitle: 'Ting',
    subtitle: (date: string, n: number) => `Rapport ${date}. ${n === 1 ? '1 ting' : `${n} ting`}.`,
    // Two choices that change the shape of the paper: headings that add up,
    // and a photo beside each thing.
    groupBy: 'Grupper etter',
    groupNone: 'Ingen',
    groupRest: (key: string) => `Uten ${key.toLocaleLowerCase('nb')}`,
    withPhotos: 'Ta med bilder',
    sum: (key: string, amount: string) => `${key}: ${amount}`,
    grandTotal: 'Til sammen',
  },
  action: {
    save: 'Lagre',
    cancel: 'Avbryt',
    close: 'Lukk',
    delete: 'Slett',
    back: 'Tilbake',
    choosePhoto: 'Velg bilde',
    changePhoto: 'Bytt bilde',
    removePhoto: 'Fjern bilde',
    // Several photos per thing: the first is the one the table and the report
    // show, and any of them can be made the first.
    addPhoto: 'Legg til bilde',
    makeFirstPhoto: 'Gjør til hovedbilde',
    firstPhoto: 'Hovedbilde',
    removePhotoAt: (n: number) => `Fjern bilde ${n}`,
  },
  add: {
    title: 'Ny ting',
    photoAlt: 'Bildet du tok',
    saved: (name: string) => `«${name}» er lagret.`,
    missingName: 'Tingen må ha et navn.',
    // The values to tap under a field, named for the field
    suggestions: (label: string) => `${label}: Forslag`,
  },
  barcode: {
    label: 'Strekkode',
    scan: 'Skann strekkode',
    scanning: 'Leser…',
    read: (format: string) => `Lest som ${format}.`,
    none: 'Fant ingen strekkode i bildet. Ta bildet nærmere, rett forfra.',
    bookHint: 'Skann strekkoden på boka, så kan du hente tittel og forfatter på nett.',
    lookup: 'Slå opp på nett',
    looking: 'Slår opp…',
    found: (source: string) => `Navnet er hentet fra ${source}. Rett det som er feil før du lagrer.`,
    notFound: 'Fant ikke koden i oppslagsverkene. Skriv navnet selv.',
    offline: 'Ingen nettforbindelse. Skriv navnet selv, eller prøv igjen senere.',
    failed: 'Oppslaget feilet. Prøv på nytt.',
  },
  detail: {
    specs: 'Egenskaper',
    photos: 'Bilder',
    noSpecs: 'Ingen egenskaper',
    notFound: 'Fant ikke denne tingen',
    photoAlt: (name: string) => `Bilde av ${name}`,
    edit: (label: string) => `Endre ${label.toLocaleLowerCase('nb')}`,
  },
  confirm: {
    delete: (name: string) => `Slett «${name}»? Du kan ikke angre.`,
    deleteMany: (n: number) => (n === 1 ? 'Slett 1 ting? Du kan ikke angre.' : `Slett ${n} ting? Du kan ikke angre.`),
    unsaved: 'Du har endringer som ikke er lagret. Forlat siden likevel?',
    saveOrDiscard: 'Du har endringer som ikke er lagret.',
    discard: 'Forkast endringene',
  },
  table: {
    selectAll: 'Velg alle',
    selectRow: (name: string) => `Velg ${name === '' ? 'ny rad' : name}`,
    name: 'Navn',
    addRow: 'Legg til ting',
    addColumn: 'Legg til egenskap',
    // Plus opens a menu: a thing (a row) or a property (a column)
    add: 'Legg til',
    addColumnMenu: 'Legg til egenskap (kolonne)',
    // Under the column form: help for the field in use. For the name, the
    // properties that already exist and start with what is typed
    columnHelp: {
      similar: 'Finnes fra før',
      everywhere: (key: string) => `«${key}» finnes i alle kategorier.`,
      here: (key: string, where: string) => `«${key}» finnes allerede i ${where}.`,
      elsewhere: (key: string, where: string) => `«${key}» finnes i ${where}.`,
      shared: (key: string, where: string, here: string) =>
        `«${key}» finnes i ${where}. Legger du den til, får ${here} den samme egenskapen.`,
      types: {
        text: 'Fritekst, som en kommentar eller et serienummer. Lenker blir klikkbare på tingens side.',
        choice: 'Faste verdier å velge mellom, som Status eller Farge. Du kan filtrere på dem og gruppere dem før utskrift.',
        number: 'Skriv bare tallet i cellene. Enheten velger du i neste felt.',
        date: 'En dato, som 19.09.26. Filteret viser årene.',
        path: 'Hele veien frem til der tingen finnes, som Loftsbod › Hylle 2 › Boks 4. Du får ett filter per nivå.',
      },
      options: 'Skriv alternativene adskilt med komma: «Bøker, Film, Musikk». Med eller uten mellomrom etter komma.',
      unit: 'Velg i lista eller skriv din egen. Kolonner i kr får en sum.',
      scope: 'Uten hake: Egenskapen knyttes til alle kategoriene.',
    },
    wrap: 'Bryt lang tekst over flere linjer',
    columnKey: 'Navn på egenskap',
    columnType: 'Felttype',
    types: { text: 'Tekst', choice: 'Valgliste', number: 'Tall', date: 'Dato', path: 'Sti' },
    columnOptions: 'Alternativer',
    columnUnit: 'Enhet',
    columnUnitOptional: 'Valgfritt',
    columnAdd: 'Legg til',
    // Symbol and the word for it: the list shows both, the column stores the symbol
    unitOptions: [
      ['kr', 'kroner'],
      ['°C', 'grader celsius'],
      ['g', 'gram'],
      ['kg', 'kilogram'],
      ['mm', 'millimeter'],
      ['cm', 'centimeter'],
      ['m', 'meter'],
      ['ml', 'milliliter'],
      ['l', 'liter'],
      ['stk', 'stykk'],
      ['år', 'år'],
    ],
    removeColumn: 'Fjern',
    // The columns the view leaves out: empty here, or the same on every row
    showMore: (n: number) => (n === 1 ? 'Vis 1 kolonne til' : `Vis ${n} kolonner til`),
    hideMore: 'Vis færre kolonner',
    // The column menu, only while one category is in view: what the column is for
    onlyIn: (category: string) => `Bruk bare i ${category}`,
    alsoIn: (category: string) => `Bruk også i ${category}`,
    notIn: (category: string) => `Ikke bruk i ${category}`,
    removeColumnConfirm: (key: string, n: number) =>
      `Egenskapen «${key}» brukes av ${n === 1 ? '1 ting' : `${n} ting`}. Fjern den fra alle? Du kan ikke angre.`,
    removeColumnAction: 'Fjern',
    columnMenu: (key: string) => `Valg for ${key}`,
    sortBy: (key: string) => `Sorter etter ${key}`,
    resize: (key: string) => `Endre bredde på ${key}`,
    resizeHint: 'Dra for å endre bredde. Dobbeltklikk for å tilpasse bredden til innholdet.',
    renameColumn: 'Endre',
    nameCannotGo: 'Du kan ikke fjerne Navn. Denne egenskapen er hva appen må ha som minimum for å vise hva du har lagt til.',
    renameSave: 'Lagre navn',
    renameCancel: 'Avbryt',
    moveLeft: 'Flytt til venstre',
    moveRight: 'Flytt til høyre',
    removeRow: 'Fjern rad',
    unsaved: (n: number) => (n === 1 ? '1 endring ikke lagret' : `${n} endringer ikke lagret`),
    cell: (name: string, col: string) => `${col} for ${name === '' ? 'ny rad' : name}`,
  },
  error: {
    saveFailed: 'Kunne ikke lagre. Prøv på nytt.',
    crashed: 'Noe gikk galt, men dataene dine er bevart. Last siden på nytt for å fortsette.',
    reload: 'Last på nytt',
    rowsMissingName: (n: number) => (n === 1 ? '1 rad mangler navn.' : `${n} rader mangler navn.`),
    columnExists: 'Denne egenskapen finnes allerede.',
    notNumbers: (n: number, key: string) => (n === 1 ? `1 verdi i ${key} er ikke et tall.` : `${n} verdier i ${key} er ikke tall.`),
    notDates: (n: number, key: string) => (n === 1 ? `1 verdi i ${key} er ikke en dato.` : `${n} verdier i ${key} er ikke datoer.`),
  },
  notice: {
    update: 'Oppdater til ny versjon',
  },
  // How to install, where the browser has no prompt of its own. Safari on an
  // iPhone keeps Del behind ••• (iOS 26 and later); on an iPad and in the
  // other iPhone browsers Del is on the bar itself.
  install: {
    prompt: 'Installer appen',
    iosMore: 'Installer: ••• › Del › Legg til på Hjem-skjerm',
    iosShare: 'Installer: Del › Legg til på Hjem-skjerm',
    macSafari: 'Installer: Del › Legg til i Dock',
    // With a passphrase: why installing matters in a browser that clears
    // the data of a site nobody opens
    evict: 'Nettleseren kan slette det du har lagt til hvis du ikke åpner appen på sju dager.',
  },
  // Before a passphrase: the line under the top bar
  trial: {
    notice: 'Du bruker appen i prøvemodus. Det du legger til, blir borte når du lukker den.',
    // A phone closes the app on its own, so the phone says when, not who
    noticePhone: 'Det du legger til blir borte når appen lukkes.',
    setPassword: 'Velg passord for å bevare det',
    why: 'Passordet krypterer alt du legger til, på enheten og i sikkerhetskopiene. Uten passord blir det borte når du lukker appen.',
    lost: 'Mister du passordet, er dataene tapt.',
    folderFirst: 'Velg et passord først. Mappen får bare krypterte data.',
    done: 'Passord valgt. Alt du har lagt til er bevart.',
  },
  storage: {
    title: 'Innstillinger',
    viewTitle: 'Tilpass visning',
    viewList: 'Egenskaper i tabellen',
    viewShown: (shown: number, total: number) => `${shown} av ${total} vises`,
    folderTitle: 'Lagringsmappe',
    folderNone:
      'Du har ikke valgt en mappe for automatisk lagring. Alt du registrerer, ligger bare i denne nettleseren. Sletter du nettstedsdata i nettleseren, blir det borte.',
    unsupported: 'Denne nettleseren kan ikke koble appen til en mappe. Bruk Chrome eller Edge. Du kan også laste ned en sikkerhetskopi under.',
    choose: 'Velg mappe',
    checking: 'Sjekker mappen…',
    needsPermission: (name: string) => `Mappen «${name}» trenger tillatelse på nytt. Fram til da lagrer appen bare i nettleseren.`,
    grant: 'Gi tilgang',
    connected: (name: string) => `Appen lagrer i mappen «${name}».`,
    lastWritten: (time: string) => `Sist lagret kl. ${time}.`,
    loaded: 'Lastet fra mappen.',
    disconnect: 'Koble fra',
    conflict: (name: string, folderCount: number, folderDate: string, localCount: number) =>
      `Mappen «${name}» inneholder ${folderCount === 1 ? '1 ting' : `${folderCount} ting`} fra ${folderDate}. I nettleseren ligger ${localCount === 1 ? '1 ting' : `${localCount} ting`}. Velg hva du vil beholde.`,
    useFolder: 'Bruk mappen',
    useLocal: 'Skriv over mappen',
    error: (name: string) => `Kunne ikke lagre i «${name}». Prøv på nytt, eller koble til mappen på nytt.`,
    copyTitle: 'Sikkerhetskopi',
    copyWhat: 'Manuelt: Én kryptert fil med alt du har lagt til. Gjenoppretter du fra filen, erstatter den alt som lå i appen fra før.',
    download: 'Last ned sikkerhetskopi',
    // A phone saves the file through the share sheet: Filer, AirDrop, e-post
    share: 'Del sikkerhetskopi',
    restore: 'Gjenopprett fra sikkerhetskopi',
    restoreConfirm: (n: number) => `Erstatt alt som ligger her med ${n === 1 ? '1 ting' : `${n} ting`} fra filen? Du kan ikke angre.`,
    restoreDone: (n: number) => `Gjenopprettet ${n === 1 ? '1 ting' : `${n} ting`}.`,
    restoreFailed: 'Denne filen er ikke en sikkerhetskopi fra Ting. Velg en fil som slutter på .json.',
    replace: 'Erstatt',
  },
} as const
